name: video-server

services:
  video:
    image: motionproject/motion
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - ./motion/config:/usr/local/etc/motion
      - ./motion/storage:/var/lib/motion
      - ./video:/media/video
    container_name: video-server-container
